"""empty message

Revision ID: 1753ad5d2521
Revises: ecc68a7d5150
Create Date: 2026-05-12 20:59:47.897876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1753ad5d2521'
down_revision = 'ecc68a7d5150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nas',
    sa.Column('nasname', sa.String(length=128), nullable=False),
    sa.Column('shortname', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('ports', sa.Integer(), nullable=True),
    sa.Column('secret', sa.String(length=128), nullable=False),
    sa.Column('server', sa.String(length=64), nullable=True),
    sa.Column('community', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('router_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nas', schema=None) as batch_op:
        batch_op.create_index('idx_nas_active', ['is_active'], unique=False)
        batch_op.create_index('idx_nas_nasname', ['nasname'], unique=False)
        batch_op.create_index('idx_nas_org', ['organization_id'], unique=False)
        batch_op.create_index('idx_nas_router', ['router_id'], unique=False)
        batch_op.create_index('idx_nas_secret', ['secret'], unique=False)
        batch_op.create_index('idx_nas_shortname', ['shortname'], unique=False)
        batch_op.create_index('idx_nas_type', ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_nas_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_nas_nasname'), ['nasname'], unique=False)
        batch_op.create_index(batch_op.f('ix_nas_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nas_router_id'), ['router_id'], unique=False)

    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('radius_secret', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('radius_configured_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('radius_config_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('nas_entry_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('auto_config_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_config_error', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_routers_nas_entry_id'), ['nas_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_routers_radius_config_status'), ['radius_config_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_routers_radius_secret'), ['radius_secret'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routers_radius_secret'))
        batch_op.drop_index(batch_op.f('ix_routers_radius_config_status'))
        batch_op.drop_index(batch_op.f('ix_routers_nas_entry_id'))
        batch_op.drop_column('last_config_error')
        batch_op.drop_column('auto_config_attempts')
        batch_op.drop_column('nas_entry_id')
        batch_op.drop_column('radius_config_status')
        batch_op.drop_column('radius_configured_at')
        batch_op.drop_column('radius_secret')

    with op.batch_alter_table('nas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nas_router_id'))
        batch_op.drop_index(batch_op.f('ix_nas_organization_id'))
        batch_op.drop_index(batch_op.f('ix_nas_nasname'))
        batch_op.drop_index(batch_op.f('ix_nas_is_active'))
        batch_op.drop_index('idx_nas_type')
        batch_op.drop_index('idx_nas_shortname')
        batch_op.drop_index('idx_nas_secret')
        batch_op.drop_index('idx_nas_router')
        batch_op.drop_index('idx_nas_org')
        batch_op.drop_index('idx_nas_nasname')
        batch_op.drop_index('idx_nas_active')

    op.drop_table('nas')
    # ### end Alembic commands ###
