"""Add proper foreign keys between routers and nas

Revision ID: 49748bf370a9
Revises: 9913d513e996
Create Date: 2026-05-12 22:34:20.863343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49748bf370a9'
down_revision = '9913d513e996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nas', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'routers', ['router_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
