"""empty message

Revision ID: 6326842ed898
Revises: 946cf31cb37e
Create Date: 2026-05-09 15:22:47.614041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6326842ed898'
down_revision = '946cf31cb37e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.alter_column('router_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.create_index('idx_ap_location', ['location'], unique=False)
        batch_op.create_index('idx_ap_mac', ['mac_address'], unique=False)
        batch_op.create_index('idx_ap_organization', ['organization_id'], unique=False)
        batch_op.create_index('idx_ap_router_status', ['router_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_points_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_points_router_id'), ['router_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('access_points_router_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'routers', ['router_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('latitude')
        batch_op.drop_column('encryption_key_encrypted')
        batch_op.drop_column('ssid_visibility')
        batch_op.drop_column('longitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.VARCHAR(length=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ssid_visibility', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('encryption_key_encrypted', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('access_points_router_id_fkey'), 'routers', ['router_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_access_points_router_id'))
        batch_op.drop_index(batch_op.f('ix_access_points_location'))
        batch_op.drop_index('idx_ap_router_status')
        batch_op.drop_index('idx_ap_organization')
        batch_op.drop_index('idx_ap_mac')
        batch_op.drop_index('idx_ap_location')
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('router_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_column('description')

    # ### end Alembic commands ###
