"""empty message

Revision ID: 7e2feffaeb9b
Revises: 6326842ed898
Create Date: 2026-05-09 23:45:30.985600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e2feffaeb9b'
down_revision = '6326842ed898'
branch_labels = None
depends_on = None


def upgrade():
    # ✅ STEP 1: Create the enum type FIRST
    op.execute("CREATE TYPE validityunit AS ENUM ('MINUTES', 'HOURS', 'DAYS', 'MONTHS', 'YEARS')")
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_session_org', ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_sessions_access_point_id'), ['access_point_id'], unique=False)

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_metadata', sa.JSON(), nullable=True))
        batch_op.drop_column('Invoice_metadata')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validity_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('validity_unit', sa.Enum('MINUTES', 'HOURS', 'DAYS', 'MONTHS', 'YEARS', name='validityunit'), nullable=True))
        batch_op.drop_column('validity_days')

    with op.batch_alter_table('radius_accounting', schema=None) as batch_op:
        batch_op.create_index('idx_radius_org', ['organization_id'], unique=False)
        batch_op.create_unique_constraint(None, ['acct_unique_id'])

    with op.batch_alter_table('voucher_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validity_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('validity_unit', sa.Enum('MINUTES', 'HOURS', 'DAYS', 'MONTHS', 'YEARS', name='validityunit'), nullable=True))

    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validity_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('validity_unit', sa.Enum('MINUTES', 'HOURS', 'DAYS', 'MONTHS', 'YEARS', name='validityunit'), nullable=True))
        batch_op.add_column(sa.Column('validity_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('data_limit_mb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('activation_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('scheduled_activation_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('activated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_column('activated_at')
        batch_op.drop_column('scheduled_activation_at')
        batch_op.drop_column('activation_type')
        batch_op.drop_column('data_limit_mb')
        batch_op.drop_column('validity_type')
        batch_op.drop_column('validity_unit')
        batch_op.drop_column('validity_value')

    with op.batch_alter_table('voucher_batches', schema=None) as batch_op:
        batch_op.drop_column('validity_unit')
        batch_op.drop_column('validity_value')

    with op.batch_alter_table('radius_accounting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_radius_org')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validity_days', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('validity_unit')
        batch_op.drop_column('validity_value')

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Invoice_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('invoice_metadata')

    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_sessions_access_point_id'))
        batch_op.drop_index('idx_session_org')

    # ✅ STEP 8: Drop the enum type on downgrade
    op.execute("DROP TYPE validityunit")
    # ### end Alembic commands ###