"""empty message

Revision ID: 7eedbf3d72cd
Revises: 
Create Date: 2026-05-09 12:08:17.774416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7eedbf3d72cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotspot_servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hotspot_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('ssl_certificate', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ssl_key_encrypted', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('login_page_theme', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('authentication_methods', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('keepalive_timeout', sa.Integer(), nullable=True))
        batch_op.alter_column('interface',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_hotspot_servers_router_id'))
        batch_op.drop_column('radius_enabled')
        batch_op.drop_column('radius_secret_encrypted')
        batch_op.drop_column('radius_server')

    with op.batch_alter_table('pppoe_servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authentication_protocols', sa.JSON(), nullable=True))
        batch_op.alter_column('interface',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_pppoe_servers_router_id'))
        batch_op.drop_column('idle_timeout')
        batch_op.drop_column('radius_interim_update')
        batch_op.drop_column('session_timeout')
        batch_op.drop_column('remote_address_pool')
        batch_op.drop_column('radius_enabled')
        batch_op.drop_column('radius_server')
        batch_op.drop_column('radius_secret_encrypted')

    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firmware_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('api_ssl_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ssh_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ssh_key_encrypted', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('last_sync_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('connection_pool_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('settings', sa.JSON(), nullable=True))
        batch_op.alter_column('password_encrypted',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_routers_network'))
        batch_op.drop_index(batch_op.f('idx_routers_org_status'))
        batch_op.drop_index(batch_op.f('ix_routers_ip_address'))
        batch_op.drop_index(batch_op.f('ix_routers_network_id'))
        batch_op.drop_constraint(batch_op.f('routers_network_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'networks', ['network_id'], ['id'])
        batch_op.drop_column('memory_usage')
        batch_op.drop_column('last_error')
        batch_op.drop_column('description')
        batch_op.drop_column('uptime_seconds')
        batch_op.drop_column('cpu_usage')
        batch_op.drop_column('capabilities')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capabilities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cpu_usage', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uptime_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('memory_usage', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('routers_network_id_fkey'), 'networks', ['network_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_routers_network_id'), ['network_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_routers_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('idx_routers_org_status'), ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_routers_network'), ['network_id'], unique=False)
        batch_op.alter_column('password_encrypted',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('settings')
        batch_op.drop_column('connection_pool_size')
        batch_op.drop_column('last_sync_at')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('ssh_key_encrypted')
        batch_op.drop_column('ssh_port')
        batch_op.drop_column('api_ssl_port')
        batch_op.drop_column('firmware_version')

    with op.batch_alter_table('pppoe_servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('radius_secret_encrypted', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('radius_server', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('radius_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('remote_address_pool', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('session_timeout', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('radius_interim_update', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('idle_timeout', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_pppoe_servers_router_id'), ['router_id'], unique=False)
        batch_op.alter_column('interface',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('authentication_protocols')

    with op.batch_alter_table('hotspot_servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('radius_server', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('radius_secret_encrypted', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('radius_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_hotspot_servers_router_id'), ['router_id'], unique=False)
        batch_op.alter_column('interface',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('keepalive_timeout')
        batch_op.drop_column('authentication_methods')
        batch_op.drop_column('login_page_theme')
        batch_op.drop_column('ssl_key_encrypted')
        batch_op.drop_column('ssl_certificate')
        batch_op.drop_column('hotspot_id')

    # ### end Alembic commands ###
