"""empty message

Revision ID: 8a8287827a32
Revises: 7e2feffaeb9b
Create Date: 2026-05-10 13:32:01.786662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8287827a32'
down_revision = '7e2feffaeb9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscriber_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_encrypted', sa.String(length=255), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.create_index('idx_subscribers_org_username', ['organization_id', 'username'], unique=True)
        batch_op.create_index('idx_subscribers_type', ['subscriber_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscribers_subscriber_type'), ['subscriber_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscribers_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscribers_username'))
        batch_op.drop_index(batch_op.f('ix_subscribers_subscriber_type'))
        batch_op.drop_index('idx_subscribers_type')
        batch_op.drop_index('idx_subscribers_org_username')
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('password_encrypted')
        batch_op.drop_column('username')
        batch_op.drop_column('subscriber_type')

    # ### end Alembic commands ###
