"""empty message

Revision ID: 946cf31cb37e
Revises: 7eedbf3d72cd
Create Date: 2026-05-09 13:19:13.324968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946cf31cb37e'
down_revision = '7eedbf3d72cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
