"""empty message

Revision ID: ecc68a7d5150
Revises: 8a8287827a32
Create Date: 2026-05-10 15:42:07.329791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc68a7d5150'
down_revision = '8a8287827a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radacct',
    sa.Column('radacctid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('acct_session_id', sa.String(length=64), nullable=False),
    sa.Column('acct_unique_id', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('groupname', sa.String(length=64), nullable=True),
    sa.Column('realm', sa.String(length=64), nullable=True),
    sa.Column('nas_ip_address', sa.String(length=15), nullable=False),
    sa.Column('nas_port_id', sa.Integer(), nullable=True),
    sa.Column('nas_port_type', sa.String(length=32), nullable=True),
    sa.Column('acct_start_time', sa.DateTime(), nullable=True),
    sa.Column('acct_stop_time', sa.DateTime(), nullable=True),
    sa.Column('acct_session_time', sa.Integer(), nullable=True),
    sa.Column('acct_input_octets', sa.Integer(), nullable=True),
    sa.Column('acct_output_octets', sa.Integer(), nullable=True),
    sa.Column('called_station_id', sa.String(length=50), nullable=True),
    sa.Column('calling_station_id', sa.String(length=50), nullable=True),
    sa.Column('acct_terminate_cause', sa.String(length=32), nullable=True),
    sa.Column('service_type', sa.String(length=32), nullable=True),
    sa.Column('framed_protocol', sa.String(length=32), nullable=True),
    sa.Column('framed_ip_address', sa.String(length=15), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('radacctid', 'id')
    )
    with op.batch_alter_table('radacct', schema=None) as batch_op:
        batch_op.create_index('idx_radacct_org', ['organization_id'], unique=False)
        batch_op.create_index('idx_radacct_session_id', ['acct_session_id'], unique=False)
        batch_op.create_index('idx_radacct_start_time', ['acct_start_time'], unique=False)
        batch_op.create_index('idx_radacct_unique_id', ['acct_unique_id'], unique=False)
        batch_op.create_index('idx_radacct_username', ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_radacct_acct_session_id'), ['acct_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_radacct_acct_unique_id'), ['acct_unique_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_radacct_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_radacct_username'), ['username'], unique=False)

    op.create_table('radcheck',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('attribute', sa.String(length=64), nullable=False),
    sa.Column('op', sa.String(length=2), nullable=False),
    sa.Column('value', sa.String(length=253), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('radcheck', schema=None) as batch_op:
        batch_op.create_index('idx_radcheck_org', ['organization_id'], unique=False)
        batch_op.create_index('idx_radcheck_username', ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_radcheck_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_radcheck_username'), ['username'], unique=False)

    op.create_table('radreply',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('attribute', sa.String(length=64), nullable=False),
    sa.Column('op', sa.String(length=2), nullable=False),
    sa.Column('value', sa.String(length=253), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('radreply', schema=None) as batch_op:
        batch_op.create_index('idx_radreply_org', ['organization_id'], unique=False)
        batch_op.create_index('idx_radreply_username', ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_radreply_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_radreply_username'), ['username'], unique=False)

    op.create_table('radusergroup',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('groupname', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('radusergroup', schema=None) as batch_op:
        batch_op.create_index('idx_radusergroup_org', ['organization_id'], unique=False)
        batch_op.create_index('idx_radusergroup_username', ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_radusergroup_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_radusergroup_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radusergroup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radusergroup_username'))
        batch_op.drop_index(batch_op.f('ix_radusergroup_organization_id'))
        batch_op.drop_index('idx_radusergroup_username')
        batch_op.drop_index('idx_radusergroup_org')

    op.drop_table('radusergroup')
    with op.batch_alter_table('radreply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radreply_username'))
        batch_op.drop_index(batch_op.f('ix_radreply_organization_id'))
        batch_op.drop_index('idx_radreply_username')
        batch_op.drop_index('idx_radreply_org')

    op.drop_table('radreply')
    with op.batch_alter_table('radcheck', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radcheck_username'))
        batch_op.drop_index(batch_op.f('ix_radcheck_organization_id'))
        batch_op.drop_index('idx_radcheck_username')
        batch_op.drop_index('idx_radcheck_org')

    op.drop_table('radcheck')
    with op.batch_alter_table('radacct', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radacct_username'))
        batch_op.drop_index(batch_op.f('ix_radacct_organization_id'))
        batch_op.drop_index(batch_op.f('ix_radacct_acct_unique_id'))
        batch_op.drop_index(batch_op.f('ix_radacct_acct_session_id'))
        batch_op.drop_index('idx_radacct_username')
        batch_op.drop_index('idx_radacct_unique_id')
        batch_op.drop_index('idx_radacct_start_time')
        batch_op.drop_index('idx_radacct_session_id')
        batch_op.drop_index('idx_radacct_org')

    op.drop_table('radacct')
    # ### end Alembic commands ###
