"""empty message

Revision ID: f248ffbfc9be
Revises: 
Create Date: 2026-06-22 15:38:02.552988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f248ffbfc9be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radpostauth')
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('wireguard_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('wireguard_public_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('wireguard_private_key_encrypted', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_routers_wireguard_ip'), ['wireguard_ip'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routers_wireguard_ip'))
        batch_op.drop_column('wireguard_private_key_encrypted')
        batch_op.drop_column('wireguard_public_key')
        batch_op.drop_column('wireguard_ip')
        batch_op.drop_column('local_ip')

    op.create_table('radpostauth',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('pass', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('reply', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('authdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('radpostauth_pkey'))
    )
    # ### end Alembic commands ###
