"""empty message

Revision ID: f24e972366c6
Revises: b6524ef7cf0a
Create Date: 2026-05-01 13:08:23.137147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f24e972366c6'
down_revision = 'b6524ef7cf0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('networks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=False))
        batch_op.create_index('idx_networks_active', ['is_active'], unique=False)
        batch_op.create_index('idx_networks_org_slug', ['organization_id', 'slug'], unique=True)
        batch_op.create_index('idx_networks_type', ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_networks_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('networks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_networks_slug'))
        batch_op.drop_index('idx_networks_type')
        batch_op.drop_index('idx_networks_org_slug')
        batch_op.drop_index('idx_networks_active')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
