"""empty message

Revision ID: 37ae56eea00c
Revises: 
Create Date: 2026-04-27 14:53:36.750997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37ae56eea00c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_status'), ['status'], unique=False)

    op.create_table('radius_accounting',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('nas_ip_address', postgresql.INET(), nullable=True),
    sa.Column('framed_ip_address', postgresql.INET(), nullable=True),
    sa.Column('called_station_id', sa.String(length=255), nullable=True),
    sa.Column('calling_station_id', sa.String(length=255), nullable=True),
    sa.Column('acct_status_type', sa.String(length=50), nullable=True),
    sa.Column('acct_start_time', sa.DateTime(), nullable=True),
    sa.Column('acct_stop_time', sa.DateTime(), nullable=True),
    sa.Column('acct_input_octets', sa.BigInteger(), nullable=True),
    sa.Column('acct_output_octets', sa.BigInteger(), nullable=True),
    sa.Column('acct_session_time', sa.Integer(), nullable=True),
    sa.Column('acct_terminate_cause', sa.String(length=100), nullable=True),
    sa.Column('acct_unique_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('radius_accounting', schema=None) as batch_op:
        batch_op.create_index('idx_radius_session', ['session_id'], unique=False)
        batch_op.create_index('idx_radius_start', ['acct_start_time'], unique=False)
        batch_op.create_index('idx_radius_username', ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_radius_accounting_acct_start_time'), ['acct_start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_radius_accounting_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_radius_accounting_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_radius_accounting_username'), ['username'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)

    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('subscriber_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_created', ['created_at'], unique=False)
        batch_op.create_index('idx_audit_user_action', ['user_id', 'action'], unique=False)

    op.create_table('discount_coupons',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('minimum_purchase', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('applicable_plan_ids', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discount_coupons', schema=None) as batch_op:
        batch_op.create_index('idx_coupons_code', ['code'], unique=False)
        batch_op.create_index('idx_coupons_valid', ['valid_from', 'valid_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_discount_coupons_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_discount_coupons_organization_id'), ['organization_id'], unique=False)

    op.create_table('networks',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('networks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_networks_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_networks_organization_id'), ['organization_id'], unique=False)

    op.create_table('organization_settings',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_settings', schema=None) as batch_op:
        batch_op.create_index('idx_org_setting_key', ['organization_id', 'key'], unique=True)

    op.create_table('organization_users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_users', schema=None) as batch_op:
        batch_op.create_index('idx_org_user_unique', ['organization_id', 'user_id'], unique=True)

    op.create_table('payment_accounts',
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('shortcode', sa.String(length=10), nullable=False),
    sa.Column('consumer_key_encrypted', sa.String(), nullable=False),
    sa.Column('consumer_secret_encrypted', sa.String(), nullable=False),
    sa.Column('passkey_encrypted', sa.String(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=True),
    sa.Column('callback_url', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('test_status', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_accounts', schema=None) as batch_op:
        batch_op.create_index('idx_payment_accounts_default', ['organization_id', 'is_default'], unique=False)
        batch_op.create_index('idx_payment_accounts_org', ['organization_id'], unique=False)
        batch_op.create_index('idx_payment_accounts_shortcode', ['shortcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_accounts_organization_id'), ['organization_id'], unique=False)

    op.create_table('payment_webhook_logs',
    sa.Column('webhook_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_webhook_logs', schema=None) as batch_op:
        batch_op.create_index('idx_webhook_processed', ['processed', 'created_at'], unique=False)
        batch_op.create_index('idx_webhook_request_id', ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_webhook_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_webhook_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_webhook_logs_request_id'), ['request_id'], unique=False)

    op.create_table('plans',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('validity_type', sa.String(length=20), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('data_limit_mb', sa.Integer(), nullable=True),
    sa.Column('bandwidth_up_mbps', sa.Integer(), nullable=True),
    sa.Column('bandwidth_down_mbps', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('setup_fee', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('discount_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('concurrent_logins', sa.Integer(), nullable=True),
    sa.Column('device_limit', sa.Integer(), nullable=True),
    sa.Column('session_timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('idle_timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('is_unlimited', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index('idx_plans_org_active', ['organization_id', 'is_active'], unique=False)
        batch_op.create_index('idx_plans_type', ['plan_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_organization_id'), ['organization_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('subscribers',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_spent', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.create_index('idx_subscribers_org_phone', ['organization_id', 'phone'], unique=True)
        batch_op.create_index('idx_subscribers_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscribers_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscribers_status'), ['status'], unique=False)

    op.create_table('devices',
    sa.Column('subscriber_id', sa.UUID(), nullable=False),
    sa.Column('mac_address', postgresql.MACADDR(), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index('idx_devices_org_mac', ['organization_id', 'mac_address'], unique=True)
        batch_op.create_index('idx_devices_subscriber', ['subscriber_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_organization_id'), ['organization_id'], unique=False)

    op.create_table('routers',
    sa.Column('network_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('api_port', sa.Integer(), nullable=True),
    sa.Column('api_ssl_port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_encrypted', sa.String(), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=True),
    sa.Column('ssh_key_encrypted', sa.String(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.String(length=10), nullable=True),
    sa.Column('longitude', sa.String(length=11), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('connection_pool_size', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_routers_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_routers_status'), ['status'], unique=False)

    op.create_table('subscriptions',
    sa.Column('subscriber_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('expiry_time', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('device_limit', sa.Integer(), nullable=True),
    sa.Column('bandwidth_up_mbps', sa.Integer(), nullable=True),
    sa.Column('bandwidth_down_mbps', sa.Integer(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('total_data_used_mb', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('last_reset_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('idx_subscriptions_expiry', ['expiry_time'], unique=False)
        batch_op.create_index('idx_subscriptions_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index('idx_subscriptions_plan', ['plan_id'], unique=False)
        batch_op.create_index('idx_subscriptions_subscriber', ['subscriber_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_expiry_time'), ['expiry_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)

    op.create_table('voucher_batches',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('batch_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_voucher', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_in_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voucher_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voucher_batches_organization_id'), ['organization_id'], unique=False)

    op.create_table('hotspot_servers',
    sa.Column('router_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hotspot_id', sa.String(length=50), nullable=False),
    sa.Column('interface', sa.String(length=50), nullable=True),
    sa.Column('address_pool', postgresql.INET(), nullable=True),
    sa.Column('dns_name', sa.String(length=255), nullable=True),
    sa.Column('ssl_certificate', sa.String(), nullable=True),
    sa.Column('ssl_key_encrypted', sa.String(), nullable=True),
    sa.Column('login_page_theme', sa.JSON(), nullable=True),
    sa.Column('authentication_methods', sa.JSON(), nullable=True),
    sa.Column('idle_timeout', sa.Integer(), nullable=True),
    sa.Column('session_timeout', sa.Integer(), nullable=True),
    sa.Column('keepalive_timeout', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hotspot_servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotspot_servers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotspot_servers_organization_id'), ['organization_id'], unique=False)

    op.create_table('invoices',
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_type', sa.String(length=20), nullable=False),
    sa.Column('subscriber_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('tax_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('discount_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('billing_period_start', sa.DateTime(), nullable=True),
    sa.Column('billing_period_end', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('idx_invoices_due_date', ['due_date'], unique=False)
        batch_op.create_index('idx_invoices_issue_date', ['issue_date'], unique=False)
        batch_op.create_index('idx_invoices_number', ['invoice_number'], unique=False)
        batch_op.create_index('idx_invoices_subscriber', ['subscriber_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoices_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)

    op.create_table('pppoe_servers',
    sa.Column('router_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('interface', sa.String(length=50), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('mtu', sa.Integer(), nullable=True),
    sa.Column('max_sessions', sa.Integer(), nullable=True),
    sa.Column('authentication_protocols', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pppoe_servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pppoe_servers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_pppoe_servers_organization_id'), ['organization_id'], unique=False)

    op.create_table('vouchers',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('price_paid', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_by_subscriber_id', sa.UUID(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_on_router_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['voucher_batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['used_by_subscriber_id'], ['subscribers.id'], ),
    sa.ForeignKeyConstraint(['used_on_router_id'], ['routers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.create_index('idx_vouchers_batch', ['batch_id'], unique=False)
        batch_op.create_index('idx_vouchers_code', ['code'], unique=False)
        batch_op.create_index('idx_vouchers_status_expiry', ['status', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vouchers_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_vouchers_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vouchers_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vouchers_status'), ['status'], unique=False)

    op.create_table('access_points',
    sa.Column('router_id', sa.UUID(), nullable=True),
    sa.Column('hotspot_server_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mac_address', postgresql.MACADDR(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('ssid', sa.String(length=32), nullable=False),
    sa.Column('ssid_visibility', sa.Boolean(), nullable=True),
    sa.Column('encryption_type', sa.String(length=20), nullable=True),
    sa.Column('encryption_key_encrypted', sa.String(), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.String(length=10), nullable=True),
    sa.Column('longitude', sa.String(length=11), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['hotspot_server_id'], ['hotspot_servers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_points_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_points_mac_address'), ['mac_address'], unique=True)
        batch_op.create_index(batch_op.f('ix_access_points_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_points_status'), ['status'], unique=False)

    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('Invoice_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('subscriber_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('payment_account_id', sa.UUID(), nullable=True),
    sa.Column('transaction_reference', sa.String(length=255), nullable=False),
    sa.Column('mpesa_receipt', sa.String(length=50), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('payment_details', sa.JSON(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('callback_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('custom_data', sa.JSON(), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_account_id'], ['payment_accounts.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_transactions_checkout', ['checkout_request_id'], unique=False)
        batch_op.create_index('idx_transactions_created', ['created_at'], unique=False)
        batch_op.create_index('idx_transactions_invoice', ['invoice_id'], unique=False)
        batch_op.create_index('idx_transactions_mpesa_receipt', ['mpesa_receipt'], unique=False)
        batch_op.create_index('idx_transactions_subscriber', ['subscriber_id', 'status'], unique=False)
        batch_op.create_index('idx_transactions_subscription', ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_checkout_request_id'), ['checkout_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_mpesa_receipt'), ['mpesa_receipt'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_reference'), ['transaction_reference'], unique=True)

    op.create_table('active_sessions',
    sa.Column('subscriber_id', sa.UUID(), nullable=True),
    sa.Column('voucher_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('router_id', sa.UUID(), nullable=True),
    sa.Column('hotspot_server_id', sa.UUID(), nullable=True),
    sa.Column('pppoe_server_id', sa.UUID(), nullable=True),
    sa.Column('access_point_id', sa.UUID(), nullable=True),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('device_mac', postgresql.MACADDR(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('nas_identifier', sa.String(length=255), nullable=True),
    sa.Column('framed_ip_address', postgresql.INET(), nullable=True),
    sa.Column('called_station_id', sa.String(length=255), nullable=True),
    sa.Column('calling_station_id', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('expiry_time', sa.DateTime(), nullable=False),
    sa.Column('bytes_in', sa.BigInteger(), nullable=True),
    sa.Column('bytes_out', sa.BigInteger(), nullable=True),
    sa.Column('session_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('termination_cause', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_points.id'], ),
    sa.ForeignKeyConstraint(['hotspot_server_id'], ['hotspot_servers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pppoe_server_id'], ['pppoe_servers.id'], ),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_session_ap', ['access_point_id', 'status'], unique=False)
        batch_op.create_index('idx_session_device', ['device_mac', 'status'], unique=False)
        batch_op.create_index('idx_session_expiry', ['expiry_time'], unique=False)
        batch_op.create_index('idx_session_router', ['router_id', 'status'], unique=False)
        batch_op.create_index('idx_session_subscriber', ['subscriber_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_sessions_device_mac'), ['device_mac'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_sessions_expiry_time'), ['expiry_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_sessions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_sessions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_sessions_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_sessions_status'), ['status'], unique=False)

    op.create_table('refunds',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('refund_reference', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('mpesa_refund_receipt', sa.String(length=50), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index('idx_refunds_reference', ['refund_reference'], unique=False)
        batch_op.create_index('idx_refunds_transaction', ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_refund_reference'), ['refund_reference'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refunds_refund_reference'))
        batch_op.drop_index(batch_op.f('ix_refunds_organization_id'))
        batch_op.drop_index('idx_refunds_transaction')
        batch_op.drop_index('idx_refunds_reference')

    op.drop_table('refunds')
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_active_sessions_start_time'))
        batch_op.drop_index(batch_op.f('ix_active_sessions_session_id'))
        batch_op.drop_index(batch_op.f('ix_active_sessions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_active_sessions_expiry_time'))
        batch_op.drop_index(batch_op.f('ix_active_sessions_device_mac'))
        batch_op.drop_index('idx_session_subscriber')
        batch_op.drop_index('idx_session_router')
        batch_op.drop_index('idx_session_expiry')
        batch_op.drop_index('idx_session_device')
        batch_op.drop_index('idx_session_ap')

    op.drop_table('active_sessions')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_reference'))
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_mpesa_receipt'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_checkout_request_id'))
        batch_op.drop_index('idx_transactions_subscription')
        batch_op.drop_index('idx_transactions_subscriber')
        batch_op.drop_index('idx_transactions_mpesa_receipt')
        batch_op.drop_index('idx_transactions_invoice')
        batch_op.drop_index('idx_transactions_created')
        batch_op.drop_index('idx_transactions_checkout')

    op.drop_table('transactions')
    op.drop_table('invoice_items')
    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_points_status'))
        batch_op.drop_index(batch_op.f('ix_access_points_organization_id'))
        batch_op.drop_index(batch_op.f('ix_access_points_mac_address'))
        batch_op.drop_index(batch_op.f('ix_access_points_is_active'))

    op.drop_table('access_points')
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vouchers_status'))
        batch_op.drop_index(batch_op.f('ix_vouchers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_vouchers_expires_at'))
        batch_op.drop_index(batch_op.f('ix_vouchers_code'))
        batch_op.drop_index('idx_vouchers_status_expiry')
        batch_op.drop_index('idx_vouchers_code')
        batch_op.drop_index('idx_vouchers_batch')

    op.drop_table('vouchers')
    with op.batch_alter_table('pppoe_servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pppoe_servers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_pppoe_servers_is_active'))

    op.drop_table('pppoe_servers')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_organization_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))
        batch_op.drop_index('idx_invoices_subscriber')
        batch_op.drop_index('idx_invoices_number')
        batch_op.drop_index('idx_invoices_issue_date')
        batch_op.drop_index('idx_invoices_due_date')

    op.drop_table('invoices')
    with op.batch_alter_table('hotspot_servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotspot_servers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_hotspot_servers_is_active'))

    op.drop_table('hotspot_servers')
    with op.batch_alter_table('voucher_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voucher_batches_organization_id'))

    op.drop_table('voucher_batches')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_expiry_time'))
        batch_op.drop_index('idx_subscriptions_subscriber')
        batch_op.drop_index('idx_subscriptions_plan')
        batch_op.drop_index('idx_subscriptions_org_status')
        batch_op.drop_index('idx_subscriptions_expiry')

    op.drop_table('subscriptions')
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routers_status'))
        batch_op.drop_index(batch_op.f('ix_routers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_routers_is_active'))

    op.drop_table('routers')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_organization_id'))
        batch_op.drop_index('idx_devices_subscriber')
        batch_op.drop_index('idx_devices_org_mac')

    op.drop_table('devices')
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscribers_status'))
        batch_op.drop_index(batch_op.f('ix_subscribers_organization_id'))
        batch_op.drop_index('idx_subscribers_status')
        batch_op.drop_index('idx_subscribers_org_phone')

    op.drop_table('subscribers')
    op.drop_table('refresh_tokens')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_organization_id'))
        batch_op.drop_index(batch_op.f('ix_plans_is_active'))
        batch_op.drop_index('idx_plans_type')
        batch_op.drop_index('idx_plans_org_active')

    op.drop_table('plans')
    with op.batch_alter_table('payment_webhook_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_webhook_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_payment_webhook_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_payment_webhook_logs_created_at'))
        batch_op.drop_index('idx_webhook_request_id')
        batch_op.drop_index('idx_webhook_processed')

    op.drop_table('payment_webhook_logs')
    with op.batch_alter_table('payment_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_accounts_organization_id'))
        batch_op.drop_index('idx_payment_accounts_shortcode')
        batch_op.drop_index('idx_payment_accounts_org')
        batch_op.drop_index('idx_payment_accounts_default')

    op.drop_table('payment_accounts')
    with op.batch_alter_table('organization_users', schema=None) as batch_op:
        batch_op.drop_index('idx_org_user_unique')

    op.drop_table('organization_users')
    with op.batch_alter_table('organization_settings', schema=None) as batch_op:
        batch_op.drop_index('idx_org_setting_key')

    op.drop_table('organization_settings')
    with op.batch_alter_table('networks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_networks_organization_id'))
        batch_op.drop_index(batch_op.f('ix_networks_is_active'))

    op.drop_table('networks')
    with op.batch_alter_table('discount_coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discount_coupons_organization_id'))
        batch_op.drop_index(batch_op.f('ix_discount_coupons_code'))
        batch_op.drop_index('idx_coupons_valid')
        batch_op.drop_index('idx_coupons_code')

    op.drop_table('discount_coupons')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_user_action')
        batch_op.drop_index('idx_audit_created')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('radius_accounting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radius_accounting_username'))
        batch_op.drop_index(batch_op.f('ix_radius_accounting_session_id'))
        batch_op.drop_index(batch_op.f('ix_radius_accounting_organization_id'))
        batch_op.drop_index(batch_op.f('ix_radius_accounting_acct_start_time'))
        batch_op.drop_index('idx_radius_username')
        batch_op.drop_index('idx_radius_start')
        batch_op.drop_index('idx_radius_session')

    op.drop_table('radius_accounting')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_status'))
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
